datasource:
  driver: ${datasource.driver}
  url: ${datasource.url}
  username: ${datasource.username}
  password: ${datasource.password}

hibernate:
  hbm2ddlAuto: ${hibernate.hbm2ddl.auto}
  showSql: ${hibernate.show-sql}
  dialect: ${hibernate.dialect}
  defaultSchema: ${spring.profiles.active}

jwt:
  accessSecret: secret
  accessExpiration: 6000000
  refreshSecret: secret
  refreshExpiration: 6000000